apiVersion: cache.platform.ohanyere.io/v1alpha1
kind: RedisClaim
metadata:
  name: audit-api-redis
  labels:
    app.kubernetes.io/name: audit-api
    finops.ohanyere.io/cost-center: developer-experience
spec:
  environment: dev
  size: small
  evictionPolicy: allkeys-lru
